### PR TITLE
ESLint 9 and eslint-plugin-cds 3 in Playground examples

### PR DESCRIPTION
**Pull request by chgeo**
- ESLint 9
- eslint-plugin-cds 3
- Updated config

### CODE REVIEW

**Comment by renejeglinsky** [comment]
@chgeo Is this a sideeffect of this PR? Or intended? Previously the rules were not in the ToC.
image

**Comment by chgeo** [comment]
Intended behavior.  This is to avoid orphaned pages w/o a sidebar entry.

**Comment by renejeglinsky** [comment]
Alright.
Is the first entry for you also with a linebreak?

**Comment by chgeo** [comment]
No break for me.. but good catch. Will make the truncation with `...` happen earlier.

**Comment by chgeo** [comment]
Or just extend the sidebar width a bit...

**Comment by chgeo** [comment]
Done.
@renejeglinsky can you pull the external repo and check again?  Also the other line break (in _SAP Business Application Studio_ or so) should be gone.

**Comment by renejeglinsky** [comment]
Yep, looks nice!
image
Thanks! :)

**Pull request merged**
