### PR TITLE
Enhanced sqlite docu for how to use in production

### PR DESCRIPTION
**Pull request by schiwekM**
Hi Rene,

I've added a block about running sqlite in production to the docu to improve guidance in valid use cases like running CAP as a proxy for S4. 

BR,
Marten

### CODE REVIEW

**Comment by renejeglinsky** [comment]
Hi Marten,

Thanks a lot! I'll discuss this and get back to you. :)

**Comment by renejeglinsky** [comment]
Hi Marten,
could you enhance the description of the scenario and the boundary conditions, like losing data when the corresponding container is dropped and restarted? The technical configuration is the easier part compared to judging and identifying if one would really want to SQLite in prod.

**Comment by schiwekM** [comment]
Hi Rene,

I encounter the issue with a partner in an S4 transformation. Basically they use their CAP app as a proxy for the S4 API and have no entities to persist. However when trying to start without any database, the server always crashed when trying to do cds.connect.to upon the request. The workaround was to just to add the sqlite db in prod as the requests are anyways forwarded to S4.

**Comment by schiwekM** [comment]
> > 4 transformation. Basically they use their CAP app as a proxy for the S4 API and have no entities to persist. However when trying to start without any database, the server always crashed when trying to do cds.connect.to upon the request. The workaround was to just to add the sqlite db in prod as the requests are anyways forwarded to S4.
> 
> I rather think that this is a configuration issue on the customer side. If you do not have any database, do not set a `cds.requires.db` entry in the package.json.

Strangely when they did not, it crashed upon requests.

**Comment by johannes-vogel** [comment]
@schiwekM Do you by any chance have a pointer for me look at the config?

**Comment by schiwekM** [comment]
> @schiwekM Do you by any chance have a pointer for me look at the config?

Send an email with contact details

**Comment by johannes-vogel** [comment]
@schiwekM I'd propose to close this PR.
I did not hear back and I'm rather sure that this is not required, if you do not have the need for a database.

**Pull request closed without merging**
