### PR TITLE
HANA native associations

### PR DESCRIPTION
**Pull request by stewsk**

### CODE REVIEW

**Comment by stewsk** [comment]
@chgeo : Please remove the sentence "For new projects, `cds add hana` automatically adds this configuration." if it won't make it into the release.

**Review by chgeo — COMMENTED** [review]
Fine for me.  Just take over the suggestions from the release note PR.

**Comment by stewsk** [comment]
> Fine for me. Just take over the suggestions from the release note PR.

done

**Review by chgeo — APPROVED** [review]

**Comment by chgeo** [comment]
@smahati can you review these docs so that we can close the topic?  Also see the release note PRs for August (which have been merge already).

**Review by smahati — APPROVED** [review]

**Pull request merged**
