### PR TITLE
Use session context variables on SQLite and H2

### PR DESCRIPTION
**Pull request by agoerler**

### CODE REVIEW

**Review by beckermarc — APPROVED** [review]

**Comment by beckermarc** [comment]
@smahati Can you please take a look at this PR?

**Review by chgeo — COMMENTED** [review]
The code snippets also need to be replaced/removed: 
- https://github.com/cap-js/docs/pull/331/files#diff-00d4b3e76a513fb636f74d2671251b9ffa562cdd966a12a662a12aa8806030dbR211-R213
- https://github.com/cap-js/docs/pull/331/files#diff-00d4b3e76a513fb636f74d2671251b9ffa562cdd966a12a662a12aa8806030dbR234-R236

**Comment by beckermarc** [comment]
@chgeo thanks, missed these. I removed them, as they are no longer needed in the latest version.

**Review by chgeo — APPROVED** [review]

**Comment by chgeo** [comment]
Let's merge this, as it's just fixing content.

**Pull request merged**
