### PR TITLE
Review java documentation

### PR DESCRIPTION
**Pull request by BraunMatthias**
Peer PR: https://github.tools.sap/cap/docs/pull/609

### CODE REVIEW

**Comment by chgeo** [comment]
@BraunMatthias I have resolved the merge conflicts that I caused with my parallel refactoring of `index.data.js` to `.ts` files.  Sorry for the confusion.

Please pull this PR + the internal repo and just should have a consistent state.
There are still a number of broken links, but that is you work in progress I guess.

**Comment by chgeo** [comment]
Hm.. looking at it.. still too many diffs not caused by you.  I guess I need to go back to square one and do the merge from main again.  Sorry, stay tuned..

**Comment by chgeo** [comment]
Alright, this should now be your intended state, i.e. only your changes.
→ Please pull the PR again.

Now, for all file moves and renames, this is quite incompatible to the current URLs.  You need to at least add `redirect_from: <old-URL>` frontmatter to be compatible.

Still, all links to the old URLs need to be adjusted as these need to use the new URL pattern.

We can also discuss how to handle this...

**Comment by BraunMatthias** [comment]
Yes, redirect links have to be added in a step afterwards. But I wanted just to see and discuss the result in a preview.

**Review by renejeglinsky — APPROVED** [review]

**Review by renejeglinsky — APPROVED** [review]

**Pull request merged**
