### PR TITLE
Config inspector

### PR DESCRIPTION
**Pull request by chgeo**
image

Usage: `<Config>cds.foo=bar</Config>` shows possible configuration variants
for this config key and value.

### CODE REVIEW

**Comment by chgeo** [comment]
@renejeglinsky @swaldmann the config inspector that I mentioned some time ago.

What do you think?
Samples in cap/docs#1110, but you can easily add you own.

**Comment by renejeglinsky** [comment]
If I select one of the options, the pop-over collapses. Tested it in Edge and Chrome. Is that expected b/c it's not 100% finished yet?
Overall I like the idea. And if it's that simple to use: very nice!

**Comment by chgeo** [comment]
> If I select one of the options, the pop-over collapses. 

This should be fixed by now.  

It's not finished indeed.  Needs some more cleanup and styling.  Syntax highlighting would be nice.
Can also discuss this today, time-permitting.

**Comment by chgeo** [comment]
Let's merge this to get more feedback by more usages.

**Pull request merged**
