### PR TITLE
@cap-js/notifications plugin documentation

### PR DESCRIPTION
**Pull request by AnmolBinani**
CAPire documentation for the [cap-js/notifications](https://github.com/cap-js/notifications) plugin

### CODE REVIEW

**Comment by renejeglinsky** [comment]
Hi @AnmolBinani ,

I learned yesterday how we're going to document plugins:
- Documentation should reside in the plugin's readme.md
- A short description and a link should be added to this new page, which has already a placeholder for Notifications: https://pages.github.tools.sap/cap/docs/plugins/#notifications

Please adapt this PR accordingly. Thanks a lot :)

**Comment by AnmolBinani** [comment]
@renejeglinsky 

In that case we don't need this PR at all right. We will simply add information in the [CAPire](https://pages.github.tools.sap/cap/docs/plugins/#notifications) and link the [CAP Plug-in](https://github.com/cap-js/notifications#readme)

**Comment by renejeglinsky** [comment]
Yes, either close this one here or reuse it for the information in the plugins section. :)

**Comment by renejeglinsky** [comment]
Now there's already some documentation filled in the plugins section by Daniel H.: https://github.com/cap-js/docs/commit/dd74aa2c1937c84a584f4361520aec3b2ebdadbb

**Pull request closed without merging**
