### PR TITLE
OpenAPI: adding openAPI annotations - externalDocs

### PR DESCRIPTION
**Pull request by RoshniNaveenaS**
Adding `externalDocs` property as per the requirement [here](https://github.tools.sap/cap/issues/issues/14181).

### CODE REVIEW

**Review by RamIndia — APPROVED** [review]
Looks Good

**Comment by RoshniNaveenaS** [comment]
Hello @renejeglinsky,
Can you have a look at this PR and let me know if I have to make any changes!

**Comment by RoshniNaveenaS** [comment]
Hello @smahati ,
Can you have a look at this PR

**Comment by RoshniNaveenaS** [comment]
Hello @renejeglinsky,
Can you have a look at this PR

**Review by renejeglinsky — APPROVED** [review]

**Pull request merged**
