### PR TITLE
cap-js-community plugins update

### PR DESCRIPTION
**Pull request by oklemenz2**

### CODE REVIEW

**Comment by oklemenz2** [comment]
@danjoa please double-check

**Comment by oklemenz2** [comment]
Can we get this in? Is it then also in internal docs?

**Review by DanSchlachter — APPROVED** [review]

**Comment by oklemenz2** [comment]
@smahati please review and approve.. thanks.

**Comment by oklemenz2** [comment]
@renejeglinsk Please check & approve

**Comment by renejeglinsky** [comment]
Hi Oliver,
Thanks a lot! As this page is supposed to contain a curated list of plugins, I need to sync with my colleagues und will get back to you.

**Comment by DanSchlachter** [comment]
Hi Rene,

I double checked this with Daniel H before approving last week, we do want websocket support to show up on the curated list.

Thanks
Daniel

**Comment by renejeglinsky** [comment]
@DanSchlachter Is the same true for Event Queue and Feature Toggle?

**Comment by DanSchlachter** [comment]
no, sorry. only confirmed websocket so far

**Comment by oklemenz2** [comment]
Any update. Can we merge and close this topic ;-)

**Comment by DanSchlachter** [comment]
for now only websockets should go in here, as the other two topics FT and Event Queue needs further discussion and might move into cap core.

**Comment by oklemenz2** [comment]
> for now only websockets should go in here, as the other two topics FT and Event Queue needs further discussion and might move into cap core.

OK. I will remove the two others

**Comment by oklemenz2** [comment]
Fo reference I store the docs for the two as comment:

```md
## Event Queue

An event queue that enables secure multi-tenant enabled transactional processing of asynchronous events, featuring instant event processing with Redis Pub/Sub and load distribution across all application instances.

![Event Queue](./assets/index/event-queue.drawio.svg)

Available for:

[![Node.js](../assets/logos/nodejs.svg 'Link to the plugins repository.'){style="height:2.5em; display:inline; margin:0 0.2em;"}](https://github.com/cap-js-community/event-queue#readme)

## Feature Toggle Library

SAP BTP feature toggle library enables Node.js applications using the SAP Cloud Application Programming Model to maintain live-updatable feature toggles via Redis.

![Feature Toggle Library Single Key Access](./assets/index/concepts-single-key.drawio.svg)


Available for:

[![Node.js](../assets/logos/nodejs.svg 'Link to the plugins repository.'){style="height:2.5em; display:inline; margin:0 0.2em;"}](https://github.com/cap-js-community/feature-toggle-library#readme)
```

**Comment by oklemenz2** [comment]
event-queue drawio
concepts-single-key drawio

**Comment by oklemenz2** [comment]
@DanSchlachter Please check again...

**Review by DanSchlachter — APPROVED** [review]

**Review by renejeglinsky — APPROVED** [review]
Thank you guys!

**Pull request merged**
