### PR TITLE
Document sidecar health indicators

### PR DESCRIPTION
**Pull request by vmikhailenko**
Document additional health indicators targeted for the next release.

### CODE REVIEW

**Review by smahati — APPROVED** [review]

**Comment by smahati** [comment]
does next here mean the september release?

**Comment by vmikhailenko** [comment]
> does next here mean the september release?

Wait, we wanted to make changes first.

**Comment by smahati** [comment]
> > does next here mean the september release?
> 
> Wait, we wanted to make changes first.

Alright, thank you for confirming.

**Comment by vmikhailenko** [comment]
> does next here mean the september release?

The feature is already merged and should be delivered in next release.

**Review by renejeglinsky — APPROVED** [review]

**Pull request merged**
