### PR TITLE
Fixes wrong class in code sample for observability

### PR DESCRIPTION
**Pull request by vmikhailenko**
Use correct class name `Meter` for the code sample.

### CODE REVIEW

**Review by StefanHenke — APPROVED** [review]

**Comment by StefanHenke** [comment]
@vmikhailenko: The dynatrace chapter is separate because you can use Dynatrace even without Open Telemetry. If we integrated the content into the telemetry chapter, people might loose this fact.

However, what I noticed is that the Dynatrace chapter only links to the official, externally available documentation on help.sap.com. For external customers, Dynatrace is not offered as a managed service on BTP. This is only for internal ones which is not mentioned at the moment. Should we add this with a corresponding (internal) link?

**Comment by vmikhailenko** [comment]
> @vmikhailenko: The dynatrace chapter is separate because you can use Dynatrace even without Open Telemetry. If we integrated the content into the telemetry chapter, people might loose this fact.
> 
> However, what I noticed is that the Dynatrace chapter only links to the official, externally available documentation on help.sap.com. For external customers, Dynatrace is not offered as a managed service on BTP. This is only for internal ones which is not mentioned at the moment. Should we add this with a corresponding (internal) link?

I asked the internal Dynatrace docu to link to us.

**Comment by vmikhailenko** [comment]
@StefanHenke How about linking this https://opentelemetry.io/docs/languages/java/instrumentation/#initialize-the-sdk?

`GlobalOpenTelemetry` is discouraged by OpenTelemetry. Maybe we should mention that to prevent the people from simply copy-pasting the snippet?

**Comment by StefanHenke** [comment]
@vmikhailenko: We have to be careful here because the OpenTelemetry config is actually injected by the Java Agent which can  collide with the sdk. We need to ensure that we do not configure Open Telemetry a second time which would result in two parallel configs. At least I failed in the past to avoid `GlobalOpenTelemetry`.

**Comment by renejeglinsky** [comment]
> @vmikhailenko: The dynatrace chapter is separate because you can use Dynatrace even without Open Telemetry. If we integrated the content into the telemetry chapter, people might loose this fact.
> 
> However, what I noticed is that the Dynatrace chapter only links to the official, externally available documentation on help.sap.com. For external customers, Dynatrace is not offered as a managed service on BTP. This is only for internal ones which is not mentioned at the moment. Should we add this with a corresponding (internal) link?

Should we also add an internal link pointing to some internal documentation?

**Review by renejeglinsky — APPROVED** [review]

**Comment by StefanHenke** [comment]
> > @vmikhailenko: The dynatrace chapter is separate because you can use Dynatrace even without Open Telemetry. If we integrated the content into the telemetry chapter, people might loose this fact.
> > However, what I noticed is that the Dynatrace chapter only links to the official, externally available documentation on help.sap.com. For external customers, Dynatrace is not offered as a managed service on BTP. This is only for internal ones which is not mentioned at the moment. Should we add this with a corresponding (internal) link?
> 
> Should we also add an internal link pointing to some internal documentation?

Today, we don´t have an internal documentation section for dynatrace. What would be the best way to just add a link for internal usage: https://pages.github.tools.sap/apm/docs/

**Comment by renejeglinsky** [comment]
> > > @vmikhailenko: The dynatrace chapter is separate because you can use Dynatrace even without Open Telemetry. If we integrated the content into the telemetry chapter, people might loose this fact.
> > > However, what I noticed is that the Dynatrace chapter only links to the official, externally available documentation on help.sap.com. For external customers, Dynatrace is not offered as a managed service on BTP. This is only for internal ones which is not mentioned at the moment. Should we add this with a corresponding (internal) link?
> > 
> > 
> > Should we also add an internal link pointing to some internal documentation?
> 
> Today, we don´t have an internal documentation section for dynatrace. What would be the best way to just add a link for internal usage?

Will reach out to you. I'll merge this PR as it's initial goal is achieved.

**Pull request merged**
